---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: bootstrap
---

```{r setup, include=FALSE}
library(flexdashboard) # fonctions pour le dashboard
library(dplyr)
library(ggplot2)
library(sf)
library(patchwork) #fonctions pour mettre plusieurs graphes dans differents panneaux
library(scales)
library(zoo)
library(plotly) #fonctions permettant de faire des graphes interactifs
library(lubridate) #fonctions facilitant la transformation des donnees calendaires

#importer les bases de donnees et shapefile

data<-read.csv("dataset1.csv")
data$date<-as.Date(data$date)
data$dob<-as.Date(data$dob)

mdg2 <- read_sf("shapefile/MDG_ADM1.shp")

day<-data%>%
  group_by(date)%>%
  arrange(date)%>%
  summarise(cases=n())%>%
  mutate(rollmean=rollmeanr(cases,7,fill=NA))
              

```




Ceci est un tableau de bord préliminaire produit à partir des données de cas de COVID-19 confirmés par laboratoire à Madagascar entre **`r first(na.omit(data$date))`**  et **`r last(na.omit(data$date))`**.

Row 
-----------------------------------------------------------------------

### Nombre de cas

```{r}

valueBox(
  value = format(sum(day$cases,na.rm=TRUE), big.mark = ","),
  caption = paste("Nombre total des cas jusqu'au",
                  format(last(day$date), format = "%B %d %Y")),
  icon = "fa-ambulance",
  color = "info"
)

```

###  moyenne cas par jour

```{r}

gauge(
  value = round(last(day$rollmean),2),
  min= 0,
  max= round(max(day$rollmean,na.rm = TRUE),0),
  label = paste("moyenne de cas \n par jour" ),
  sectors = gaugeSectors(
    success = c(0,1/3*max(day$rollmean,na.rm = TRUE)),
    warning = c(1/3*max(day$rollmean,na.rm = TRUE),2/3*max(day$rollmean,na.rm = TRUE)),
    danger = c(2/3*max(day$rollmean,na.rm = TRUE),max(day$rollmean,na.rm = TRUE))
  )
)

```

### cas dernier jour

```{r}

valueBox(
  value = format(last(day$cases), big.mark = ","),
  caption = paste("Nombre de cas rapportes le",
                  format(last(day$date), format = "%B %d %Y")),
  icon = "fa-flask",
  color = "warning"
)

```


Row 
-----------------------------------------------------------------------


### Série temporelle des cas.

La figure suivante présente l’évolution du nombre de cas  par jour à Madagascar.


```{r, warning=FALSE}


cas_jour<-ggplot(day)+
  geom_col(aes(x=date,y=cases))+
  geom_line(aes(x=date,y=rollmean),color="red")+
  theme(legend.position = "none", 
        panel.background = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m-%d")

ggplotly(cas_jour)


```


Row 
-----------------------------------------------------------------------

### 

```{r}


```

### Map of cases

```{r}

```

